#!/usr/bin/env node
/**
 * Convert the MySQL dump `pharmaceutical_data_full.sql` into PostgreSQL-compatible
 * INSERT statements (data only -- the DDL is hand-written in db/migrations/001).
 *
 * The only genuinely tricky part is string literals: mysqldump emits backslash
 * escapes inside single-quoted strings, which PostgreSQL does not understand
 * under standard_conforming_strings=on. We tokenise each statement and re-emit
 * literals using SQL-standard quote doubling.
 */
import { createReadStream, createWriteStream } from 'node:fs';
import { createInterface } from 'node:readline';
import process from 'node:process';

const SRC = process.argv[2];
const OUT = process.argv[3];
if (!SRC || !OUT) {
  console.error('usage: node scripts/mysql2pg.mjs <input.sql> <output.sql>');
  process.exit(1);
}

/** Tables we carry over, in FK-safe insertion order. */
const TABLE_ORDER = [
  'company', 'district', 'occupation', 'specialty', 'pregnancy_category',
  'systemic_class', 'therapeutic_class', 'indication',
  'generic', 'brand', 'sponsored_brand',
  'indication_generic', 'therapeutic_generic',
  'herbal_generic', 'herbal_brand',
];

const chr = (code) => String.fromCharCode(code);
const BACKSLASH = chr(92);
const NUL = chr(0);
const QUOTE = chr(39);

/** MySQL backslash-escape sequences -> the character they denote. */
const MYSQL_ESCAPES = new Map([
  ['0', NUL],
  [QUOTE, QUOTE],
  [chr(34), chr(34)],       // \"
  ['b', chr(8)],
  ['n', chr(10)],
  ['r', chr(13)],
  ['t', chr(9)],
  ['Z', chr(26)],
  [BACKSLASH, BACKSLASH],
  ['%', BACKSLASH + '%'],   // \% and \_ keep their backslash in MySQL
  ['_', BACKSLASH + '_'],
]);

/**
 * Rewrite the VALUES payload of a mysqldump INSERT into standard SQL.
 * Returns null if the payload cannot be parsed (caller then skips the row set).
 */
function convertValues(src) {
  let out = '';
  let i = 0;
  const n = src.length;
  while (i < n) {
    const ch = src[i];
    if (ch === QUOTE) {
      // Consume one MySQL string literal, decode escapes, re-emit standard.
      let raw = '';
      let closed = false;
      i++;
      while (i < n) {
        const c = src[i];
        if (c === BACKSLASH) {
          const next = src[i + 1];
          if (next === undefined) return null;
          raw += MYSQL_ESCAPES.has(next) ? MYSQL_ESCAPES.get(next) : next;
          i += 2;
          continue;
        }
        if (c === QUOTE) {
          if (src[i + 1] === QUOTE) { raw += QUOTE; i += 2; continue; }
          i++;
          closed = true;
          break;
        }
        raw += c;
        i++;
      }
      if (!closed) return null;
      // NUL bytes are illegal in PostgreSQL text; drop them.
      raw = raw.split(NUL).join('');
      out += QUOTE + raw.split(QUOTE).join(QUOTE + QUOTE) + QUOTE;
      continue;
    }
    if (ch === '`') { i++; continue; } // backtick identifiers
    out += ch;
    i++;
  }
  return out;
}

const insertRe = /^INSERT INTO `([a-z_]+)` VALUES (.+);\s*$/i;

const perTable = new Map(TABLE_ORDER.map((t) => [t, []]));
let skipped = 0;

const rl = createInterface({
  input: createReadStream(SRC, { encoding: 'utf8' }),
  crlfDelay: Infinity,
});

for await (const line of rl) {
  const m = line.match(insertRe);
  if (!m) continue;
  const [, table, values] = m;
  if (!perTable.has(table)) { skipped++; continue; }
  const converted = convertValues(values);
  if (converted === null) {
    console.warn(`! unparsable INSERT for ${table}, skipped`);
    skipped++;
    continue;
  }
  perTable.get(table).push(converted);
}

const out = createWriteStream(OUT, { encoding: 'utf8' });
out.write('-- Generated by scripts/mysql2pg.mjs -- do not edit by hand.\n');
out.write('-- Source: pharmaceutical_data_full.sql (mysqldump)\n\n');
out.write('BEGIN;\n\n');

for (const table of TABLE_ORDER) {
  const chunks = perTable.get(table);
  if (!chunks.length) { console.warn(`! no rows found for ${table}`); continue; }
  out.write(`-- ${table}\n`);
  for (const values of chunks) out.write(`INSERT INTO ${table} VALUES ${values};\n`);
  out.write('\n');
  console.log(`${table.padEnd(20)} ${chunks.length} insert statement(s)`);
}

// Realign the sequences behind the bigserial surrogate keys.
out.write("SELECT setval(pg_get_serial_sequence('indication_generic','id'),  COALESCE((SELECT MAX(id) FROM indication_generic), 1));\n");
out.write("SELECT setval(pg_get_serial_sequence('therapeutic_generic','id'), COALESCE((SELECT MAX(id) FROM therapeutic_generic), 1));\n");
out.write("SELECT setval(pg_get_serial_sequence('sponsored_brand','id'),     COALESCE((SELECT MAX(id) FROM sponsored_brand), 1));\n");
out.write('\nCOMMIT;\n');
out.end();

await new Promise((r) => out.on('finish', r));
console.log(`\nwrote ${OUT} (${skipped} statement(s) skipped)`);
